/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        theme: {
          bg: 'var(--bg-app)',
          card: 'var(--bg-card)',
          cardSec: 'var(--bg-card-secondary)',
          cardSubtle: 'var(--bg-card-subtle)',
          header: 'var(--bg-header)',
          sidebar: 'var(--bg-sidebar)',
          sidebarCard: 'var(--bg-sidebar-card)',
          sidebarInner: 'var(--bg-sidebar-inner)',
          border: 'var(--border-color)',
          borderSubtle: 'var(--border-subtle)',
          borderStrong: 'var(--border-strong)',
          text: 'var(--text-main)',
          body: 'var(--text-body)',
          muted: 'var(--text-muted)',
          dim: 'var(--text-dim)',
          accent: 'var(--color-accent)',
          accentHover: 'var(--color-accent-hover)',
          accentSubtle: 'var(--color-accent-subtle)',
          accentText: 'var(--color-accent-text)',
          accentBorder: 'var(--color-accent-border)',
        },
        rail: {
          base: 'var(--bg-app)',
          surface: 'var(--bg-card)',
          surfaceElevated: 'var(--bg-card-secondary)',
          surfaceHover: 'var(--bg-card-subtle)',
          surfaceActive: 'var(--bg-card-subtle)',
          text: 'var(--text-main)',
          muted: 'var(--text-muted)',
          faint: 'var(--text-dim)',
          border: 'var(--border-color)',
          borderDark: 'var(--border-strong)',
          primary: 'var(--color-accent)',
          primaryHover: 'var(--color-accent-hover)',
          primaryLight: 'var(--color-accent-subtle)',
          secondary: '#38BDF8',
          secondaryHover: '#0EA5E9',
          secondaryLight: '#082F49',
          critical: '#EF4444',
          criticalLight: '#450A0A',
          warning: '#F59E0B',
          warningLight: '#451A03',
          success: '#10B981',
          successLight: '#064E3B',
          eng: '#38BDF8',
          trd: '#F59E0B',
          snt: '#A855F7',
          admin: 'var(--color-accent)',
        }
      },
      fontFamily: {
        sans: ['Inter', 'IBM Plex Sans', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
      },
      borderRadius: {
        sm: '4px',
        md: '8px',
        lg: '12px',
        xl: '16px',
      },
      boxShadow: {
        'glow-orange': '0 0 20px -5px rgba(249, 115, 22, 0.3)',
        'glow-emerald': '0 0 20px -5px rgba(16, 185, 129, 0.3)',
        'glow-cyan': '0 0 20px -5px rgba(56, 189, 248, 0.3)',
        'card-dark': '0 4px 20px -2px rgba(0, 0, 0, 0.5)',
      }
    },
  },
  plugins: [],
}
