/**
 * COA (Control Office Application) Mock API
 * Provides live train schedules, passenger hard constraints, and goods forecast soft constraints.
 * Supports both KLK-SML (Kalka-Shimla Heritage) and NDLS-MTJ (Delhi-Mathura Trunk) corridors.
 */

export const mockPassengerTimetable = [
  // --- Kalka - Shimla Corridor (KLK-SML) Trains (Exact match to RailNet reference) ---
  {
    trainNumber: '52452',
    trainName: 'Kalka Mail',
    category: 'Heritage Express',
    origin: 'KLK',
    destination: 'SML',
    corridor: 'KLK-SML',
    trackLine: 'Main Track',
    departure: '06:10',
    arrival: '11:35',
    duration: '5h 25m',
    days: 'Daily',
    speedKmH: 28,
    seats: [
      { class: '1A', available: true },
      { class: '2A', available: true },
      { class: '3A', available: true },
      { class: 'SL', available: true },
      { class: '2S', available: true }
    ],
    status: 'On Time',
    isHardConstraint: true,
    constraintType: 'NON_NEGOTIABLE',
    priorityRank: 1,
    notes: 'Morning tourist express on UNESCO heritage line.'
  },
  {
    trainNumber: '12013',
    trainName: 'Shivalik Express',
    category: 'Deluxe Heritage',
    origin: 'KLK',
    destination: 'SML',
    corridor: 'KLK-SML',
    trackLine: 'Main Track',
    departure: '07:20',
    arrival: '12:50',
    duration: '5h 30m',
    days: 'Daily',
    speedKmH: 30,
    seats: [
      { class: '1A', available: true },
      { class: '2A', available: true },
      { class: '3A', available: true },
      { class: 'SL', available: true },
      { class: '2S', available: false }
    ],
    status: 'On Time',
    isHardConstraint: true,
    constraintType: 'NON_NEGOTIABLE',
    priorityRank: 1,
    notes: 'Connecting service from Howrah Kalka Mail.'
  },
  {
    trainNumber: '52456',
    trainName: 'Himalayan Queen',
    category: 'Express',
    origin: 'KLK',
    destination: 'SML',
    corridor: 'KLK-SML',
    trackLine: 'Main Track',
    departure: '09:15',
    arrival: '14:50',
    duration: '5h 35m',
    days: 'Mon, Wed, Fri',
    speedKmH: 26,
    seats: [
      { class: '1A', available: true },
      { class: '2A', available: true },
      { class: '3A', available: true },
      { class: 'SL', available: true },
      { class: '2S', available: false }
    ],
    status: 'On Time',
    isHardConstraint: true,
    constraintType: 'NON_NEGOTIABLE',
    priorityRank: 2,
    notes: 'Tourist panorama service.'
  },
  {
    trainNumber: '12027',
    trainName: 'Himachal Express',
    category: 'Superfast',
    origin: 'KLK',
    destination: 'SML',
    corridor: 'KLK-SML',
    trackLine: 'Main Track',
    departure: '11:40',
    arrival: '17:10',
    duration: '5h 30m',
    days: 'Daily',
    speedKmH: 29,
    seats: [
      { class: '1A', available: true },
      { class: '2A', available: true },
      { class: '3A', available: true },
      { class: 'SL', available: false },
      { class: '2S', available: false }
    ],
    status: 'On Time',
    isHardConstraint: true,
    constraintType: 'NON_NEGOTIABLE',
    priorityRank: 2,
    notes: 'Midday connector.'
  },
  {
    trainNumber: '52460',
    trainName: 'Kalka–Shimla Passenger',
    category: 'Passenger Local',
    origin: 'KLK',
    destination: 'SML',
    corridor: 'KLK-SML',
    trackLine: 'Main Track',
    departure: '13:05',
    arrival: '18:45',
    duration: '5h 40m',
    days: 'Daily',
    speedKmH: 25,
    seats: [
      { class: '1A', available: true },
      { class: '2A', available: true },
      { class: '3A', available: true },
      { class: 'SL', available: false },
      { class: '2S', available: false }
    ],
    status: 'On Time',
    isHardConstraint: true,
    constraintType: 'NON_NEGOTIABLE',
    priorityRank: 3,
    notes: 'Local station feeder service.'
  },
  {
    trainNumber: '12033',
    trainName: 'Snowfall Express',
    category: 'Special Tourist',
    origin: 'KLK',
    destination: 'SML',
    corridor: 'KLK-SML',
    trackLine: 'Main Track',
    departure: '15:20',
    arrival: '21:00',
    duration: '5h 40m',
    days: 'Tue, Thu, Sat',
    speedKmH: 27,
    seats: [
      { class: '1A', available: true },
      { class: '2A', available: true },
      { class: '3A', available: true },
      { class: 'SL', available: false },
      { class: '2S', available: false }
    ],
    status: 'On Time',
    isHardConstraint: true,
    constraintType: 'NON_NEGOTIABLE',
    priorityRank: 2,
    notes: 'Evening scenic departure.'
  },
  {
    trainNumber: '52468',
    trainName: 'Shivalik Deluxe',
    category: 'Deluxe',
    origin: 'KLK',
    destination: 'SML',
    corridor: 'KLK-SML',
    trackLine: 'Main Track',
    departure: '17:50',
    arrival: '23:25',
    duration: '5h 35m',
    days: 'Daily',
    speedKmH: 28,
    seats: [
      { class: '1A', available: true },
      { class: '2A', available: true },
      { class: '3A', available: true },
      { class: 'SL', available: false },
      { class: '2S', available: false }
    ],
    status: 'On Time',
    isHardConstraint: true,
    constraintType: 'NON_NEGOTIABLE',
    priorityRank: 1,
    notes: 'Evening dining service.'
  },
  {
    trainNumber: '12041',
    trainName: 'Kalka–Shimla Express',
    category: 'Express',
    origin: 'KLK',
    destination: 'SML',
    corridor: 'KLK-SML',
    trackLine: 'Main Track',
    departure: '19:10',
    arrival: '00:50 (+1)',
    duration: '5h 40m',
    days: 'Daily',
    speedKmH: 27,
    seats: [
      { class: '1A', available: true },
      { class: '2A', available: true },
      { class: '3A', available: false },
      { class: 'SL', available: true },
      { class: '2S', available: true }
    ],
    status: 'On Time',
    isHardConstraint: true,
    constraintType: 'NON_NEGOTIABLE',
    priorityRank: 2,
    notes: 'Night departure.'
  },
  {
    trainNumber: '52474',
    trainName: 'Himalayan Special',
    category: 'Holiday Special',
    origin: 'KLK',
    destination: 'SML',
    corridor: 'KLK-SML',
    trackLine: 'Main Track',
    departure: '21:30',
    arrival: '03:10 (+1)',
    duration: '5h 40m',
    days: 'Fri, Sat, Sun',
    speedKmH: 26,
    seats: [
      { class: '1A', available: true },
      { class: '2A', available: true },
      { class: '3A', available: true },
      { class: 'SL', available: false },
      { class: '2S', available: false }
    ],
    status: 'On Time',
    isHardConstraint: true,
    constraintType: 'NON_NEGOTIABLE',
    priorityRank: 2,
    notes: 'Weekend night express.'
  },
  {
    trainNumber: '12049',
    trainName: 'Heritage Express',
    category: 'Heritage Steam/Diesel',
    origin: 'KLK',
    destination: 'SML',
    corridor: 'KLK-SML',
    trackLine: 'Main Track',
    departure: '22:15',
    arrival: '04:00 (+1)',
    duration: '5h 45m',
    days: 'Mon, Wed, Fri',
    speedKmH: 24,
    seats: [
      { class: '1A', available: true },
      { class: '2A', available: true },
      { class: '3A', available: true },
      { class: 'SL', available: false },
      { class: '2S', available: true }
    ],
    status: 'On Time',
    isHardConstraint: true,
    constraintType: 'NON_NEGOTIABLE',
    priorityRank: 2,
    notes: 'Night sleeper service.'
  },
  {
    trainNumber: '52480',
    trainName: 'Kalka–Shimla Passenger',
    category: 'Passenger',
    origin: 'KLK',
    destination: 'SML',
    corridor: 'KLK-SML',
    trackLine: 'Main Track',
    departure: '23:50',
    arrival: '05:30 (+1)',
    duration: '5h 40m',
    days: 'Daily',
    speedKmH: 25,
    seats: [
      { class: '1A', available: true },
      { class: '2A', available: true },
      { class: '3A', available: false },
      { class: 'SL', available: true },
      { class: '2S', available: false }
    ],
    status: 'On Time',
    isHardConstraint: true,
    constraintType: 'NON_NEGOTIABLE',
    priorityRank: 3,
    notes: 'Overnight local passenger.'
  },
  {
    trainNumber: '12057',
    trainName: 'Toy Train (Special)',
    category: 'Heritage Special',
    origin: 'KLK',
    destination: 'SML',
    corridor: 'KLK-SML',
    trackLine: 'Main Track',
    departure: '01:20',
    arrival: '07:05',
    duration: '5h 45m',
    days: 'Sat, Sun',
    speedKmH: 0,
    seats: [
      { class: '1A', available: false },
      { class: '2A', available: false },
      { class: '3A', available: false },
      { class: 'SL', available: false },
      { class: '2S', available: false }
    ],
    status: 'Maintenance',
    isHardConstraint: false,
    constraintType: 'MAINTENANCE_POSSESSION',
    priorityRank: 4,
    notes: 'Track block scheduled: Barog Tunnel #33 USFD inspection & sleeper packing.'
  },

  // --- Delhi – Mathura Trunk Corridor (NDLS-MTJ) Trains ---
  {
    trainNumber: '22436',
    trainName: 'Vande Bharat Express',
    category: 'Superfast Premium',
    origin: 'NDLS',
    destination: 'BSB',
    corridor: 'NDLS-MTJ',
    section: 'NDLS-MTJ',
    trackLine: 'DN Line',
    departure: '06:00',
    arrival: '07:18',
    duration: '1h 18m',
    days: 'Daily except Thu',
    speedKmH: 130,
    seats: [
      { class: '1A', available: true },
      { class: '2A', available: true },
      { class: '3A', available: true },
      { class: 'SL', available: false },
      { class: '2S', available: true }
    ],
    status: 'On Time',
    isHardConstraint: true,
    constraintType: 'NON_NEGOTIABLE',
    priorityRank: 1,
    notes: 'Premium high-speed passenger path (130 km/h); zero detention tolerance.'
  },
  {
    trainNumber: '12952',
    trainName: 'Mumbai Central Tejas Rajdhani',
    category: 'Rajdhani',
    origin: 'NDLS',
    destination: 'MMCT',
    corridor: 'NDLS-MTJ',
    section: 'NDLS-MTJ',
    trackLine: 'DN Line',
    departure: '16:55',
    arrival: '18:05',
    duration: '1h 10m',
    days: 'Daily',
    speedKmH: 128,
    seats: [
      { class: '1A', available: true },
      { class: '2A', available: true },
      { class: '3A', available: true },
      { class: 'SL', available: true },
      { class: '2S', available: false }
    ],
    status: 'On Time',
    isHardConstraint: true,
    constraintType: 'NON_NEGOTIABLE',
    priorityRank: 1,
    notes: 'Non-negotiable trunk mail/express priority path.'
  },
  {
    trainNumber: '12004',
    trainName: 'Lucknow Swarna Shatabdi',
    category: 'Shatabdi',
    origin: 'NDLS',
    destination: 'LJN',
    corridor: 'NDLS-MTJ',
    section: 'NDLS-MTJ',
    trackLine: 'DN Line',
    departure: '06:10',
    arrival: '07:25',
    duration: '1h 15m',
    days: 'Daily',
    speedKmH: 125,
    seats: [
      { class: '1A', available: true },
      { class: '2A', available: true },
      { class: '3A', available: true },
      { class: 'SL', available: false },
      { class: '2S', available: true }
    ],
    status: 'On Time',
    isHardConstraint: true,
    constraintType: 'NON_NEGOTIABLE',
    priorityRank: 1,
    notes: 'High priority morning commuter express.'
  },
  {
    trainNumber: '12424',
    trainName: 'Dibrugarh Rajdhani Express',
    category: 'Rajdhani',
    origin: 'NDLS',
    destination: 'DBRG',
    corridor: 'NDLS-MTJ',
    section: 'NDLS-MTJ',
    trackLine: 'UP Line',
    departure: '10:05',
    arrival: '11:15',
    duration: '1h 10m',
    days: 'Daily',
    speedKmH: 120,
    seats: [
      { class: '1A', available: true },
      { class: '2A', available: true },
      { class: '3A', available: false },
      { class: 'SL', available: true },
      { class: '2S', available: false }
    ],
    status: 'On Time',
    isHardConstraint: true,
    constraintType: 'NON_NEGOTIABLE',
    priorityRank: 1,
    notes: 'Protected path.'
  },
  {
    trainNumber: '12626',
    trainName: 'Kerala Express',
    category: 'Superfast Mail',
    origin: 'NDLS',
    destination: 'TVC',
    corridor: 'NDLS-MTJ',
    section: 'NDLS-MTJ',
    trackLine: 'DN Line',
    departure: '20:10',
    arrival: '21:30',
    duration: '1h 20m',
    days: 'Daily',
    speedKmH: 105,
    seats: [
      { class: '1A', available: true },
      { class: '2A', available: true },
      { class: '3A', available: true },
      { class: 'SL', available: true },
      { class: '2S', available: true }
    ],
    status: 'On Time',
    isHardConstraint: true,
    constraintType: 'NON_NEGOTIABLE',
    priorityRank: 2,
    notes: 'Heavy passenger occupancy trunk line train.'
  },
  {
    trainNumber: '64064',
    trainName: 'Palwal - Delhi EMU Local',
    category: 'Suburban Commuter',
    origin: 'PWL',
    destination: 'NDLS',
    corridor: 'NDLS-MTJ',
    section: 'NZM-PWL',
    trackLine: 'UP Line',
    departure: '08:15',
    arrival: '09:20',
    duration: '1h 05m',
    days: 'Daily except Sun',
    speedKmH: 95,
    seats: [
      { class: '1A', available: false },
      { class: '2A', available: false },
      { class: '3A', available: false },
      { class: 'SL', available: false },
      { class: '2S', available: true }
    ],
    status: 'Delayed (8 min)',
    isHardConstraint: true,
    constraintType: 'NON_NEGOTIABLE',
    priorityRank: 2,
    notes: 'Suburban peak hours; no disruption permitted.'
  }
];

export const mockGoodsForecast = [
  {
    forecastId: 'GF-BOXN-902',
    rakeType: 'BOXN Rake (Thermal Coal)',
    origin: 'TKD Yard',
    destination: 'Dadri NTPC',
    corridor: 'NDLS-MTJ',
    section: 'NDLS-MTJ',
    trackLine: 'UP Line',
    estimatedWindow: '01:30 - 04:00',
    isHardConstraint: false,
    constraintType: 'SOFT_CONSTRAINT',
    flexibility: 'High',
    maxDetentionToleratedMinutes: 90,
    alternateRoutingAvailable: true,
    alternateRoute: 'Via Tuglakabad 3rd Goods By-pass Line',
    notes: 'Soft constraint: can be regulated in Tuglakabad yard or diverted to 3rd Line to accommodate joint maintenance possession.'
  },
  {
    forecastId: 'GF-BTPN-411',
    rakeType: 'BTPN Tanker (POL / Petroleum)',
    origin: 'Mathura Refinery',
    destination: 'Shakurbasti IOCL',
    corridor: 'NDLS-MTJ',
    section: 'PWL-MTJ',
    trackLine: 'DN Line',
    estimatedWindow: '02:15 - 04:30',
    isHardConstraint: false,
    constraintType: 'SOFT_CONSTRAINT',
    flexibility: 'Medium',
    maxDetentionToleratedMinutes: 60,
    alternateRoutingAvailable: true,
    alternateRoute: 'Loop Line Holding at Kosi Kalan',
    notes: 'Soft constraint: can hold at Kosi Kalan siding during track tamping window.'
  },
  {
    forecastId: 'GF-CONCOR-108',
    rakeType: 'CONCOR High-Cube Container',
    origin: 'Khatuwas ICB',
    destination: 'TKD ICD',
    corridor: 'NDLS-MTJ',
    section: 'NZM-PWL',
    trackLine: 'DN Line',
    estimatedWindow: '13:00 - 15:30',
    isHardConstraint: false,
    constraintType: 'SOFT_CONSTRAINT',
    flexibility: 'High',
    maxDetentionToleratedMinutes: 120,
    alternateRoutingAvailable: false,
    notes: 'Afternoon freight movement; flexible dispatch window.'
  }
];

export async function fetchPassengerTimetable(corridorId = 'KLK-SML') {
  await new Promise((r) => setTimeout(r, 100));
  if (!corridorId || corridorId === 'ALL') return mockPassengerTimetable;
  return mockPassengerTimetable.filter(t => t.corridor === corridorId);
}

export async function fetchGoodsForecast(corridorId = 'NDLS-MTJ') {
  await new Promise((r) => setTimeout(r, 100));
  if (!corridorId || corridorId === 'ALL') return mockGoodsForecast;
  return mockGoodsForecast.filter(g => g.corridor === corridorId);
}
