import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { getRequestsByDepartment, acceptAlternativeSlot } from '../../services/requests';
import { REQUEST_STAGES } from '../../constants/departments';
import { Card, CardHeader, CardTitle, CardContent, CardFooter } from '../../components/ui/Card';
import { Button } from '../../components/ui/Button';
import { Badge } from '../../components/ui/Badge';
import { PriorityTag } from '../../components/shared/PriorityTag';
import { RequestStatusBadge } from '../../components/shared/RequestStatusBadge';
import {
  Sparkles,
  Calendar,
  Clock,
  CheckCircle2,
  AlertTriangle,
  ArrowRight,
  ShieldCheck,
  Flame,
  Layers,
  HelpCircle
} from 'lucide-react';

export const ScheduledWorkView = () => {
  const [requests, setRequests] = useState([]);
  const [loading, setLoading] = useState(true);
  const [actionSuccessMessage, setActionSuccessMessage] = useState('');

  useEffect(() => {
    async function load() {
      setLoading(true);
      const data = await getRequestsByDepartment('ENG');
      setRequests(data);
      setLoading(false);
    }
    load();
  }, []);

  const scheduledRequests = requests.filter(r => r.status === REQUEST_STAGES.SCHEDULED || r.status === REQUEST_STAGES.APPROVED_OVERRIDDEN);
  const alternativeRequests = requests.filter(r => r.status === REQUEST_STAGES.ALTERNATIVE_SUGGESTED || r.status === REQUEST_STAGES.CANNOT_BE_ACCOMMODATED);

  const handleAcceptAlternative = async (requestId, altId) => {
    try {
      await acceptAlternativeSlot(requestId, altId);
      setActionSuccessMessage(`Alternative slot for ${requestId} accepted and locked into corridor schedule.`);
      // Reload
      const updated = await getRequestsByDepartment('ENG');
      setRequests(updated);
      setTimeout(() => setActionSuccessMessage(''), 4000);
    } catch (err) {
      alert('Failed to accept alternative slot.');
    }
  };

  return (
    <div className="space-y-6">
      {/* Top Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-2 border-b border-rail-border">
        <div>
          <h2 className="text-lg font-bold text-rail-text tracking-tight flex items-center gap-2">
            <span>Scheduled Track Possessions & AI Optimization Decisions</span>
            <span className="text-xs font-mono px-2 py-0.5 bg-[#EEF3EE] text-rail-success rounded-sm border border-rail-success/30 font-semibold">
              {scheduledRequests.length} Active Blocks
            </span>
          </h2>
          <p className="text-xs text-rail-muted mt-0.5">
            Automated block allocation generated by combinatorial optimization. Review detailed plain-language rationale behind each schedule decision.
          </p>
        </div>
      </div>

      {actionSuccessMessage && (
        <div className="p-3 bg-rail-successLight border border-rail-success/40 text-rail-success rounded-sm text-xs flex items-center gap-2 font-medium">
          <CheckCircle2 className="w-4 h-4" />
          <span>{actionSuccessMessage}</span>
        </div>
      )}

      {/* Section 1: Conflict & Alternative Handling (If any unaccommodated requests) */}
      {alternativeRequests.length > 0 && (
        <div className="space-y-4">
          <div className="flex items-center gap-2">
            <AlertTriangle className="w-4 h-4 text-rail-warning" />
            <h3 className="text-sm font-bold text-rail-text uppercase tracking-wider">
              Preferred Window Unaccommodated — AI Alternative Slots Proposed ({alternativeRequests.length})
            </h3>
          </div>

          {alternativeRequests.map((req) => (
            <Card key={req.id} className="border-rail-warning/60 bg-[#FAF7EE]">
              <CardHeader className="bg-[#FAF3E0]">
                <div className="flex flex-col sm:flex-row sm:items-center justify-between w-full gap-2">
                  <div className="flex items-center gap-2 flex-wrap">
                    <span className="font-mono text-xs font-bold text-rail-text">{req.id}</span>
                    <RequestStatusBadge status={req.status} />
                    <span className="text-xs font-semibold text-rail-text">{req.maintenanceType}</span>
                    <span className="text-xs text-rail-muted">({req.assetName})</span>
                  </div>
                  <PriorityTag priority={req.declaredPriority} />
                </div>
              </CardHeader>
              <CardContent className="space-y-4 p-5">
                {/* Conflict Explanation Box */}
                <div className="p-3.5 bg-rail-criticalLight/30 border border-rail-critical/30 rounded-sm text-xs space-y-1">
                  <span className="font-bold text-rail-critical flex items-center gap-1.5">
                    <AlertTriangle className="w-3.5 h-3.5" />
                    Conflict Reason (Preferred Window: {req.preferredWindow}):
                  </span>
                  <p className="text-rail-text leading-relaxed">
                    {req.conflictReason}
                  </p>
                </div>

                {/* Plain language explanation from engine */}
                {req.aiExplanation && (
                  <div className="p-3.5 bg-rail-surface border border-rail-border rounded-sm text-xs space-y-1.5">
                    <span className="font-semibold text-rail-text flex items-center gap-1.5">
                      <Sparkles className="w-3.5 h-3.5 text-rail-primary" />
                      AI Optimization Assessment:
                    </span>
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-[11px] text-rail-muted">
                      <div>
                        <strong>Capacity Gaps: </strong> {req.aiExplanation.timetableGaps}
                      </div>
                      <div>
                        <strong>Freight Coordination: </strong> {req.aiExplanation.goodsImpact}
                      </div>
                    </div>
                  </div>
                )}

                {/* Suggested Alternative Slots */}
                <div>
                  <h4 className="text-xs font-bold text-rail-text uppercase tracking-wider mb-2.5">
                    Select a Conflict-Free Alternative Slot:
                  </h4>
                  <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
                    {(req.alternatives || []).map((alt) => (
                      <div
                        key={alt.id}
                        className={`p-3.5 rounded-sm border flex flex-col justify-between transition-all ${
                          alt.recommended
                            ? 'bg-[#EEF5F1] border-rail-success shadow-xs'
                            : 'bg-rail-surface border-rail-border hover:border-rail-borderDark'
                        }`}
                      >
                        <div>
                          <div className="flex items-center justify-between mb-1.5">
                            <span className="font-mono text-[11px] font-bold text-rail-text">
                              Option {alt.id}
                            </span>
                            {alt.recommended && (
                              <span className="text-[9px] font-mono uppercase bg-rail-success text-white px-1.5 py-0.2 rounded-sm font-semibold">
                                Recommended
                              </span>
                            )}
                          </div>
                          <div className="text-xs font-bold text-rail-text">
                            {alt.timeWindow}
                          </div>
                          <div className="text-[11px] text-rail-muted font-mono mt-0.5">
                            Date: {alt.slotDate}
                          </div>
                          <p className="text-[11px] text-rail-muted mt-2 leading-relaxed">
                            {alt.impactScore}
                          </p>
                        </div>
                        <div className="mt-3 pt-2 border-t border-rail-border/60 flex items-center justify-between">
                          <span className="text-[10px] font-mono text-rail-primary font-semibold">
                            Confidence: {alt.confidence}%
                          </span>
                          <Button
                            size="sm"
                            variant={alt.recommended ? 'default' : 'outline'}
                            onClick={() => handleAcceptAlternative(req.id, alt.id)}
                          >
                            Accept Slot
                          </Button>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              </CardContent>
              <CardFooter className="bg-[#FAF4E6] flex items-center justify-between">
                <span className="text-xs text-rail-muted">
                  Cannot accept any of these proposed alternative slots?
                </span>
                <div className="flex items-center gap-2">
                  <Link to={`/eng/human-review?id=${req.id}`}>
                    <Button size="sm" variant="outline">
                      Escalate to Human Review Appeal
                    </Button>
                  </Link>
                </div>
              </CardFooter>
            </Card>
          ))}
        </div>
      )}

      {/* Section 2: Confirmed Scheduled Work with Plain-Language Explanations */}
      <div className="space-y-4">
        <h3 className="text-sm font-bold text-rail-text uppercase tracking-wider flex items-center gap-2">
          <CheckCircle2 className="w-4 h-4 text-rail-success" />
          <span>Confirmed Block Schedule & Optimization Rationale</span>
        </h3>

        <div className="grid grid-cols-1 gap-4">
          {scheduledRequests.map((req) => (
            <Card key={req.id} className="overflow-hidden">
              <CardHeader className="bg-[#F2ECE1]">
                <div className="flex flex-col sm:flex-row sm:items-center justify-between w-full gap-2">
                  <div className="flex items-center gap-2.5 flex-wrap">
                    <span className="font-mono text-xs font-bold text-rail-text">{req.id}</span>
                    <RequestStatusBadge status={req.status} />
                    <span className="text-sm font-bold text-rail-text">{req.maintenanceType}</span>
                    <span className="text-xs text-rail-muted">• {req.assetName}</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <div className="text-xs font-mono bg-[#EAE3D5] text-rail-text px-2 py-0.5 rounded-sm border border-rail-border">
                      Priority Score: <strong>{req.score}/100</strong>
                    </div>
                    <PriorityTag priority={req.declaredPriority} />
                  </div>
                </div>
              </CardHeader>

              <CardContent className="p-5 space-y-4">
                {/* Scheduled Slot Details */}
                <div className="grid grid-cols-1 sm:grid-cols-4 gap-3 bg-[#FAF7F0] p-3 rounded-sm border border-rail-border">
                  <div>
                    <span className="text-[10px] uppercase font-mono text-rail-muted block">Scheduled Date</span>
                    <span className="text-xs font-bold text-rail-text mt-0.5 block flex items-center gap-1">
                      <Calendar className="w-3.5 h-3.5 text-rail-primary" />
                      {req.scheduledSlot?.date}
                    </span>
                  </div>
                  <div>
                    <span className="text-[10px] uppercase font-mono text-rail-muted block">Possession Window</span>
                    <span className="text-xs font-bold text-rail-text mt-0.5 block flex items-center gap-1">
                      <Clock className="w-3.5 h-3.5 text-rail-primary" />
                      {req.scheduledSlot?.timeWindow}
                    </span>
                  </div>
                  <div>
                    <span className="text-[10px] uppercase font-mono text-rail-muted block">Track & Location</span>
                    <span className="text-xs font-semibold text-rail-text mt-0.5 block truncate">
                      {req.scheduledSlot?.trackLine} • {req.location}
                    </span>
                  </div>
                  <div>
                    <span className="text-[10px] uppercase font-mono text-rail-muted block">Granted Duration</span>
                    <span className="text-xs font-bold text-rail-text mt-0.5 block font-mono">
                      {req.scheduledSlot?.durationMinutes} Minutes
                    </span>
                  </div>
                </div>

                {/* AI Decision & Plain-Language Explanation Panel */}
                {req.aiExplanation && (
                  <div className="p-4 bg-[#F2EDE2] border border-rail-border rounded-sm space-y-3">
                    <div className="flex items-center justify-between">
                      <h4 className="text-xs font-bold text-rail-text uppercase tracking-wider flex items-center gap-1.5">
                        <Sparkles className="w-4 h-4 text-rail-primary" />
                        <span>AI Optimization Decision Rationale</span>
                      </h4>
                      <span className="text-[10px] font-mono text-rail-muted">
                        Corridor Engine v2.4
                      </span>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs">
                      {/* What drove the priority score */}
                      <div>
                        <span className="font-semibold text-rail-text block mb-1">
                          1. What drove the Priority Score ({req.score}/100):
                        </span>
                        <ul className="text-[11px] text-rail-muted space-y-1 list-disc list-inside bg-rail-surface p-2.5 rounded-sm border border-rail-border/70">
                          {req.aiExplanation.priorityDrivers?.map((driver, idx) => (
                            <li key={idx} className="leading-relaxed">{driver}</li>
                          ))}
                        </ul>
                      </div>

                      {/* Timetable gap & Goods forecast analysis */}
                      <div className="space-y-2">
                        <div>
                          <span className="font-semibold text-rail-text block">
                            2. Passenger Timetable Feasibility:
                          </span>
                          <p className="text-[11px] text-rail-muted mt-0.5 leading-relaxed bg-rail-surface p-2 rounded-sm border border-rail-border/70">
                            {req.aiExplanation.timetableGaps}
                          </p>
                        </div>
                        <div>
                          <span className="font-semibold text-rail-text block">
                            3. Goods Freight Routing:
                          </span>
                          <p className="text-[11px] text-rail-muted mt-0.5 leading-relaxed bg-rail-surface p-2 rounded-sm border border-rail-border/70">
                            {req.aiExplanation.goodsImpact}
                          </p>
                        </div>
                      </div>
                    </div>

                    {/* Cross-Department Co-Location / Bundling */}
                    {req.aiExplanation.bundledDepartments && (
                      <div className="p-3 bg-[#EEF5F1] border border-rail-success/40 rounded-sm text-xs space-y-1">
                        <div className="flex items-center gap-1.5 font-bold text-rail-success">
                          <CheckCircle2 className="w-4 h-4" />
                          <span>Cross-Department Multi-Activity Bundling Active</span>
                        </div>
                        <p className="text-rail-text text-[11px] leading-relaxed">
                          {req.aiExplanation.bundlingBenefit || 'Co-located with parallel department work to avoid duplicate possessions.'}
                        </p>
                        <div className="flex items-center gap-2 mt-1.5">
                          <span className="text-[10px] uppercase font-mono text-rail-muted">Bundled Departments:</span>
                          {req.aiExplanation.bundledDepartments.map((dept, i) => (
                            <span key={i} className="text-[10px] font-bold bg-white text-rail-primary px-2 py-0.5 rounded-sm border border-rail-primary/30">
                              {dept}
                            </span>
                          ))}
                        </div>
                      </div>
                    )}
                  </div>
                )}
              </CardContent>

              <CardFooter className="flex items-center justify-between">
                <Link to={`/eng/requests?id=${req.id}`} className="text-xs text-rail-primary hover:underline font-semibold flex items-center gap-1">
                  View Complete Lifecycle History <ArrowRight className="w-3 h-3" />
                </Link>
                <div className="flex items-center gap-2">
                  <Link to={`/eng/human-review?id=${req.id}`}>
                    <Button size="sm" variant="ghost">
                      Appeal Decision
                    </Button>
                  </Link>
                  <Button size="sm" variant="outline" onClick={() => window.print()}>
                    Print Block Memo
                  </Button>
                </div>
              </CardFooter>
            </Card>
          ))}
        </div>
      </div>
    </div>
  );
};
