import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '../../context/AuthContext';
import { getRequestsByDepartment, acceptAlternativeSlot } from '../../services/requests';
import { REQUEST_STAGES } from '../../constants/departments';
import { Card, CardHeader, CardContent, CardFooter } from '../../components/ui/Card';
import { Button } from '../../components/ui/Button';
import { PriorityTag } from '../../components/shared/PriorityTag';
import { RequestStatusBadge } from '../../components/shared/RequestStatusBadge';
import {
  Sparkles,
  Calendar,
  Clock,
  CheckCircle2,
  AlertTriangle,
  ArrowRight,
  Printer
} from 'lucide-react';

export const ScheduledWorkView = () => {
  const { currentRole } = useAuth();
  const deptKey = currentRole === 'ADMIN' ? 'ENG' : currentRole;

  const [requests, setRequests] = useState([]);
  const [actionSuccessMessage, setActionSuccessMessage] = useState('');

  useEffect(() => {
    async function load() {
      const data = await getRequestsByDepartment(deptKey);
      setRequests(data);
    }
    load();
  }, [deptKey]);

  const scheduledRequests = requests.filter(r => r.status === REQUEST_STAGES.SCHEDULED || r.status === REQUEST_STAGES.APPROVED_OVERRIDDEN);
  const alternativeRequests = requests.filter(r => r.status === REQUEST_STAGES.ALTERNATIVE_SUGGESTED || r.status === REQUEST_STAGES.CANNOT_BE_ACCOMMODATED);

  const handleAcceptAlternative = async (requestId, altId) => {
    try {
      await acceptAlternativeSlot(requestId, altId);
      setActionSuccessMessage(`Alternative slot for ${requestId} accepted and locked into corridor schedule.`);
      const updated = await getRequestsByDepartment(deptKey);
      setRequests(updated);
      setTimeout(() => setActionSuccessMessage(''), 4000);
    } catch (err) {
      alert('Failed to accept alternative slot.');
    }
  };

  return (
    <div className="space-y-6">
      {/* Top Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-3 border-b border-[#1F2937]">
        <div>
          <h2 className="text-lg font-bold text-slate-100 tracking-tight flex items-center gap-2">
            <span>Scheduled Track Possessions & AI Decisions</span>
            <span className="text-xs font-mono px-2 py-0.5 bg-emerald-500/10 text-emerald-400 rounded border border-emerald-500/30 font-semibold">
              {scheduledRequests.length} Active Blocks
            </span>
          </h2>
          <p className="text-xs text-slate-400 mt-1">
            Automated block allocation generated by combinatorial optimization. Inspect detailed plain-language rationale behind each schedule decision.
          </p>
        </div>
      </div>

      {actionSuccessMessage && (
        <div className="p-3 bg-emerald-500/10 border border-emerald-500/40 text-emerald-400 rounded-md text-xs flex items-center gap-2 font-semibold">
          <CheckCircle2 className="w-4 h-4" />
          <span>{actionSuccessMessage}</span>
        </div>
      )}

      {/* Section 1: Conflict & Alternative Handling (If any unaccommodated requests) */}
      {alternativeRequests.length > 0 && (
        <div className="space-y-4">
          <div className="flex items-center gap-2">
            <AlertTriangle className="w-4 h-4 text-amber-400" />
            <h3 className="text-xs font-bold text-amber-400 uppercase tracking-wider">
              Preferred Window Unaccommodated — AI Alternative Slots Proposed ({alternativeRequests.length})
            </h3>
          </div>

          {alternativeRequests.map((req) => (
            <Card key={req.id} className="border-amber-500/40 bg-[#111827]">
              <CardHeader className="bg-amber-500/10 border-b border-amber-500/20">
                <div className="flex flex-col sm:flex-row sm:items-center justify-between w-full gap-2">
                  <div className="flex items-center gap-2 flex-wrap">
                    <span className="font-mono text-xs font-bold text-orange-400">{req.id}</span>
                    <RequestStatusBadge status={req.status} />
                    <span className="text-xs font-semibold text-slate-200">{req.maintenanceType}</span>
                    <span className="text-xs text-slate-400">({req.assetName})</span>
                  </div>
                  <PriorityTag priority={req.declaredPriority} />
                </div>
              </CardHeader>
              <CardContent className="space-y-4 p-5">
                {/* Conflict Explanation Box */}
                <div className="p-3.5 bg-red-500/10 border border-red-500/30 rounded-md text-xs space-y-1">
                  <span className="font-bold text-red-400 flex items-center gap-1.5">
                    <AlertTriangle className="w-3.5 h-3.5" />
                    Conflict Reason (Preferred Window: {req.preferredWindow}):
                  </span>
                  <p className="text-slate-300 leading-relaxed">
                    {req.conflictReason}
                  </p>
                </div>

                {/* Plain language explanation from engine */}
                {req.aiExplanation && (
                  <div className="p-3.5 bg-[#0B0F17] border border-[#1F2937] rounded-md text-xs space-y-1.5">
                    <span className="font-semibold text-orange-400 flex items-center gap-1.5">
                      <Sparkles className="w-3.5 h-3.5 text-orange-400" />
                      AI Optimization Assessment:
                    </span>
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-[11px] text-slate-400">
                      <div>
                        <strong className="text-slate-300">Capacity Gaps: </strong> {req.aiExplanation.timetableGaps}
                      </div>
                      <div>
                        <strong className="text-slate-300">Freight Coordination: </strong> {req.aiExplanation.goodsImpact}
                      </div>
                    </div>
                  </div>
                )}

                {/* Suggested Alternative Slots */}
                <div>
                  <h4 className="text-xs font-bold text-slate-200 uppercase tracking-wider mb-2.5">
                    Select a Conflict-Free Alternative Slot:
                  </h4>
                  <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
                    {(req.alternatives || []).map((alt) => (
                      <div
                        key={alt.id}
                        className={`p-3.5 rounded-lg border flex flex-col justify-between transition-all ${
                          alt.recommended
                            ? 'bg-[#0B0F17] border-emerald-500/60 shadow-lg shadow-emerald-500/10'
                            : 'bg-[#0B0F17] border-[#1F2937] hover:border-slate-600'
                        }`}
                      >
                        <div>
                          <div className="flex items-center justify-between mb-1.5">
                            <span className="font-mono text-[11px] font-bold text-slate-200">
                              Option {alt.id}
                            </span>
                            {alt.recommended && (
                              <span className="text-[9px] font-mono uppercase bg-emerald-500 text-slate-900 px-1.5 py-0.5 rounded font-bold">
                                Recommended
                              </span>
                            )}
                          </div>
                          <div className="text-xs font-bold text-slate-100">
                            {alt.timeWindow}
                          </div>
                          <div className="text-[11px] text-slate-400 font-mono mt-0.5">
                            Date: {alt.slotDate}
                          </div>
                          <p className="text-[11px] text-slate-400 mt-2 leading-relaxed">
                            {alt.impactScore}
                          </p>
                        </div>
                        <div className="mt-3 pt-2 border-t border-[#1F2937] flex items-center justify-between">
                          <span className="text-[10px] font-mono text-orange-400 font-semibold">
                            Confidence: {alt.confidence}%
                          </span>
                          <Button
                            size="sm"
                            variant={alt.recommended ? 'default' : 'outline'}
                            onClick={() => handleAcceptAlternative(req.id, alt.id)}
                          >
                            Accept Slot
                          </Button>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              </CardContent>
              <CardFooter className="bg-[#0B0F17]/80 border-t border-[#1F2937] flex items-center justify-between">
                <span className="text-xs text-slate-400">
                  Cannot accept any of these proposed alternative slots?
                </span>
                <Link to={`/${deptKey.toLowerCase()}/human-review?id=${req.id}`}>
                  <Button size="sm" variant="outline">
                    Escalate to Human Review Appeal
                  </Button>
                </Link>
              </CardFooter>
            </Card>
          ))}
        </div>
      )}

      {/* Section 2: Confirmed Scheduled Work with Plain-Language Explanations */}
      <div className="space-y-4">
        <h3 className="text-xs font-bold text-slate-300 uppercase tracking-wider flex items-center gap-2">
          <CheckCircle2 className="w-4 h-4 text-emerald-400" />
          <span>Confirmed Block Schedule & Optimization Rationale</span>
        </h3>

        <div className="grid grid-cols-1 gap-4">
          {scheduledRequests.map((req) => (
            <Card key={req.id} className="overflow-hidden border-[#1F2937]">
              <CardHeader className="bg-[#1F2937]/60 border-b border-[#1F2937]">
                <div className="flex flex-col sm:flex-row sm:items-center justify-between w-full gap-2">
                  <div className="flex items-center gap-2.5 flex-wrap">
                    <span className="font-mono text-xs font-bold text-orange-400">{req.id}</span>
                    <RequestStatusBadge status={req.status} />
                    <span className="text-sm font-bold text-slate-100">{req.maintenanceType}</span>
                    <span className="text-xs text-slate-400">• {req.assetName}</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <div className="text-xs font-mono bg-[#0B0F17] text-slate-200 px-2.5 py-1 rounded border border-[#1F2937]">
                      AI Urgency Score: <strong className="text-orange-400">{req.score}/100</strong>
                    </div>
                    <PriorityTag priority={req.declaredPriority} />
                  </div>
                </div>
              </CardHeader>

              <CardContent className="p-5 space-y-4">
                {/* Scheduled Slot Details */}
                <div className="grid grid-cols-1 sm:grid-cols-4 gap-3 bg-[#0B0F17] p-3 rounded-lg border border-[#1F2937]">
                  <div>
                    <span className="text-[10px] uppercase font-mono text-slate-500 block">Scheduled Date</span>
                    <span className="text-xs font-bold text-slate-200 mt-0.5 block flex items-center gap-1">
                      <Calendar className="w-3.5 h-3.5 text-orange-400" />
                      {req.scheduledSlot?.date}
                    </span>
                  </div>
                  <div>
                    <span className="text-[10px] uppercase font-mono text-slate-500 block">Possession Window</span>
                    <span className="text-xs font-bold text-slate-200 mt-0.5 block flex items-center gap-1">
                      <Clock className="w-3.5 h-3.5 text-orange-400" />
                      {req.scheduledSlot?.timeWindow}
                    </span>
                  </div>
                  <div>
                    <span className="text-[10px] uppercase font-mono text-slate-500 block">Track & Location</span>
                    <span className="text-xs font-semibold text-slate-200 mt-0.5 block truncate">
                      {req.scheduledSlot?.trackLine} • {req.location}
                    </span>
                  </div>
                  <div>
                    <span className="text-[10px] uppercase font-mono text-slate-500 block">Granted Duration</span>
                    <span className="text-xs font-bold text-emerald-400 mt-0.5 block font-mono">
                      {req.scheduledSlot?.durationMinutes} Minutes
                    </span>
                  </div>
                </div>

                {/* AI Decision & Plain-Language Explanation Panel */}
                {req.aiExplanation && (
                  <div className="p-4 bg-[#0B0F17] border border-[#1F2937] rounded-lg space-y-3">
                    <div className="flex items-center justify-between">
                      <h4 className="text-xs font-bold text-orange-400 uppercase tracking-wider flex items-center gap-1.5">
                        <Sparkles className="w-4 h-4 text-orange-400" />
                        <span>AI Optimization Decision Rationale</span>
                      </h4>
                      <span className="text-[10px] font-mono text-slate-500">
                        Corridor Engine v2.4
                      </span>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs">
                      {/* What drove the priority score */}
                      <div>
                        <span className="font-semibold text-slate-200 block mb-1">
                          1. Priority Drivers ({req.score}/100):
                        </span>
                        <ul className="text-[11px] text-slate-400 space-y-1 list-disc list-inside bg-[#111827] p-2.5 rounded border border-[#1F2937]">
                          {req.aiExplanation.priorityDrivers?.map((driver, idx) => (
                            <li key={idx} className="leading-relaxed">{driver}</li>
                          ))}
                        </ul>
                      </div>

                      {/* Timetable gap & Goods forecast analysis */}
                      <div className="space-y-2">
                        <div>
                          <span className="font-semibold text-slate-200 block">
                            2. Passenger Timetable Feasibility:
                          </span>
                          <p className="text-[11px] text-slate-400 mt-0.5 leading-relaxed bg-[#111827] p-2 rounded border border-[#1F2937]">
                            {req.aiExplanation.timetableGaps}
                          </p>
                        </div>
                        <div>
                          <span className="font-semibold text-slate-200 block">
                            3. Goods Freight Routing:
                          </span>
                          <p className="text-[11px] text-slate-400 mt-0.5 leading-relaxed bg-[#111827] p-2 rounded border border-[#1F2937]">
                            {req.aiExplanation.goodsImpact}
                          </p>
                        </div>
                      </div>
                    </div>

                    {/* Cross-Department Co-Location / Bundling */}
                    {req.aiExplanation.bundledDepartments && (
                      <div className="p-3 bg-emerald-500/10 border border-emerald-500/30 rounded-md text-xs space-y-1">
                        <div className="flex items-center gap-1.5 font-bold text-emerald-400">
                          <CheckCircle2 className="w-4 h-4" />
                          <span>Cross-Department Multi-Activity Bundling Active</span>
                        </div>
                        <p className="text-slate-300 text-[11px] leading-relaxed">
                          {req.aiExplanation.bundlingBenefit || 'Co-located with parallel department work to avoid duplicate possessions.'}
                        </p>
                        <div className="flex items-center gap-2 mt-1.5">
                          <span className="text-[10px] uppercase font-mono text-slate-400">Bundled Departments:</span>
                          {req.aiExplanation.bundledDepartments.map((dept, i) => (
                            <span key={i} className="text-[10px] font-bold bg-[#111827] text-orange-400 px-2 py-0.5 rounded border border-[#1F2937]">
                              {dept}
                            </span>
                          ))}
                        </div>
                      </div>
                    )}
                  </div>
                )}
              </CardContent>

              <CardFooter className="bg-[#111827] border-t border-[#1F2937] flex items-center justify-between">
                <Link to={`/${deptKey.toLowerCase()}/requests?id=${req.id}`} className="text-xs text-orange-400 hover:text-orange-300 font-semibold flex items-center gap-1">
                  View Full Lifecycle History <ArrowRight className="w-3 h-3" />
                </Link>
                <div className="flex items-center gap-2">
                  <Link to={`/${deptKey.toLowerCase()}/human-review?id=${req.id}`}>
                    <Button size="sm" variant="ghost">
                      Appeal Decision
                    </Button>
                  </Link>
                  <Button size="sm" variant="outline" onClick={() => window.print()} icon={Printer}>
                    Print Block Memo
                  </Button>
                </div>
              </CardFooter>
            </Card>
          ))}
        </div>
      </div>
    </div>
  );
};
